# Generated by Django 3.2.16 on 2024-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20241028_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='iimage',
            new_name='image',
        ),
    ]
